### ISSUE TITLE
hook的方法名是什么呢？

### ISSUE THREAD

**Issue by noniu** [yiShanXin/Android-hls#2]
hook的方法名是什么呢？

**Comment by yiShanXin** [comment]
@tangzipeng 关键方法名 都采用 截图 / 文字 ！ 在文章都可以找得到 
      比如 51CTO   com.google.android.exoplayer.core.PlayerFragment  onPlayLocal
      比如 慕课       由于采用 jni处理方式关键流信息, java 层只知道aes 处理方式,以及 key byte[]，是靠程序逻辑分析得到 key
